name = "AeroNouveau"
author = "CinaedPH"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5623f35e5d08d08972b4240cc359905c5a4458096653e0ab5319bc7b531720a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
