name = "AeroNouveau"
author = "CinaedPH"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "691be9c89ac8a5bf92d0b5860df62f5dd6a6fc9b7108027eb4271d3092429598"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
