name = "AeroNouveau"
author = "CinaedPH"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24a2d4132f6828b99d78ff58121e15fa47905bd760997a2b6eef7cb5b2ed6a5b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
