version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
everycomp = true
mcwfences = true
farmersdelight = true
createdeliveryrequired = true
integratedtunnels = true
extra_gauges = true
mcwstairs = true
refurbished_furniture = true
copycats = true
comforts = true
integratedterminals = true
village_taverns = true
yigd = true
ars_technica = true
aether = true
railways = true
ars_creo = true
ccredstonelinkbridge = true
rechiseledcreate = true
biomesoplenty = true
create_radar = true
toms_peripherals = true
ars_controle = true
tradeworks = true
spell_engine = true
offroad = true
naturalist = true
supplementaries = true
cccbridge = true
createbigcannons = true
createthrusters = true
ldlib2 = true
create = true
yungscavebiomes = true
advancedperipherals = true
creatingspace = true
createenchantablemachinery = true
minecraft = true
create_connected = true
trading_floor = true
createaddition = true
sophisticatedstorage = true
powergrid = true
sliceanddice = true
enderstorage = true
creeperoverhaul = true
illagerinvasion = true
integratedcrafting = true
mcwroofs = true
mcwwindows = true
createpropulsion = true
simplyswords = true
integratedscripting = true
endersourcejars = true
oceansdelight = true
numismatics = true
quark = true
betterend = true
ends_delight = true
integratednbt = true
createdieselgenerators = true
mcwpaths = true
create_enchantment_industry = true
mcwtrpdoors = true
integratedrest = true
escalated = true
mcwlights = true
bellsandwhistles = true
amendments = true
createcobblestone = true
coffee_delight = true
moonlight = true
sophisticatedbackpacks = true
integrateddynamics = true
mca = true
mcwdoors = true
create_hypertube = true
ubesdelight = true
chipped = true
arsdelight = true
aeronautics = true
createcasing = true
simulated = true
interiors = true
deep_aether = true
rogues = true
create_dragons_plus = true
lootr = true
ars_additions = true
createdeco = true
regions_unexplored = true
ccpe = true
create_mobile_packages = true
jewelry = true
ars_elemental = true
archers = true
ars_nouveau = true
computercraft = true
sauce = true
aethersdelight = true
rechiseled = true
